# Generated by Django 4.2 on 2024-08-30 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Production Beverage', 'Production Beverage'), ('QC Beverage', 'QC Beverage'), ('WH Beverage', 'WH Beverage'), ('Utility', 'Utility'), ('GA', 'GA'), ('HR', 'HR'), ('Sales', 'Sales'), ('Finance', 'Finance'), ('Maintenance', 'Maintenance')], max_length=50)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.BooleanField(default=True)),
                ('approver', models.BooleanField(default=False)),
                ('acknowledger', models.BooleanField(default=False)),
                ('dept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
