# Generated by Django 4.2 on 2024-09-02 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_accounts_doc_controller'),
        ('dcc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('number', models.CharField(max_length=200)),
                ('rev_number', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('acknowledger', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='acknowledged', to='account.accounts')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='approved', to='account.accounts')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='created', to='account.accounts')),
                ('dept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.department')),
                ('doc_controller', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='doc_controlled', to='account.accounts')),
                ('parents', models.ManyToManyField(blank=True, related_name='children', to='dcc.document')),
                ('prev_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revised_versions', to='dcc.document')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_date', models.DateTimeField(auto_now_add=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(max_length=2000)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcc.document')),
                ('submiter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.accounts')),
            ],
        ),
        migrations.DeleteModel(
            name='Documents',
        ),
    ]
