# Generated by Django 4.2 on 2024-09-02 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcc', '0002_document_submission_delete_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='level',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=3),
        ),
    ]
