# Generated by Django 4.2 on 2024-09-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcc', '0003_document_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('obsolete', 'obsolete'), ('destroyed', 'destroyed'), ('draft', 'draft')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='upload_doc',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='submission',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('onreview', 'onreview'), ('onack', 'onack'), ('approved', 'approved'), ('rejected', 'rejected')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='submission',
            name='status_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
