# Generated by Django 4.2 on 2024-09-12 03:45

import dcc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcc', '0004_document_status_document_upload_doc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='upload_doc',
            field=models.FileField(blank=True, null=True, upload_to=dcc.models.upload_to),
        ),
    ]
