# Generated by Django 4.2 on 2024-09-17 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcc', '0005_alter_document_upload_doc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='approved_date',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='status',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='status_update',
        ),
        migrations.CreateModel(
            name='SubmissionInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('onreview', 'onreview'), ('onack', 'onack'), ('approved', 'approved'), ('rejected', 'rejected')], default='draft', max_length=20)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('notes', models.CharField(blank=True, max_length=2000, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcc.submission')),
            ],
        ),
    ]
