# Generated by Django 4.2 on 2024-09-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcc', '0006_remove_submission_approved_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
